### ISSUE TITLE
Google Storage

### ISSUE THREAD

**Issue by elfassy** [markevans/dragonfly#175]
Any way to use google cloud storage? 
https://developers.google.com/storage/docs/pricingandterms

I know carrierwave uses the Fog gem to do this, is there a similar approach with Dragonfly?
We could make something like: 
https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/storage/fog.rb

**Comment by makwanahemant** [comment]
Hi, It would be great if you provide the config for google cloud storage

**Comment by luxflux** [comment]
I created a gem for this now, it's using `google-cloud-storage` instead of `fog`: https://rubygems.org/gems/dragonfly-google_data_store
