### ISSUE TITLE
502 Bad Gateway with Rails with S3 + Passenger + nginx

### ISSUE THREAD

**Issue by vincenzor** [markevans/dragonfly#186]
Hi,

I have a problem using Rails 3.2 + Passengner + nginx + S3 (or FileStorage), I always have 502 Bad Gateway errors when accessing to:

http://host/media/xxxxx/xxxx.jpg

Basicaly, it's this problem:
https://github.com/markevans/dragonfly/issues/33

I have tried everything again and again and nothing works... Do you have a solution ??

Thx

**Comment by jplethier** [comment]
@vincenzor how did you solve this problem?
