### ISSUE TITLE
webp support?

### ISSUE THREAD

**Issue by lephyrius** [markevans/dragonfly#276]
Please add option to encode the images in WebP format.

Also it would be nice to make it possible to add the option of "interlace Plane" for the progressive JPEGs fallback.

**Comment by loureirorg** [comment]
unfortunatelly, Ubuntu ImageMagick doesn't support webp. You can check this by executing `convert -list format` at your shell prompt. If you want to follow the progress and discover why they don't support, check the official discussion: https://bugs.launchpad.net/ubuntu/+source/imagemagick/+bug/1117481

Alternatively, you can install the cwebp tool (`sudo apt-get install webp`) and create a custom processor in DragonFly. At your `initalizers/dragonfly.rb`, inside of `Dragonfly.app.configure do`, put this:

```ruby
  processor :webp do |content, *args|
    content.shell_update do |old_path, new_path|
        "/usr/bin/cwebp #{old_path} -o #{new_path}.webp"
    end
  end
```

Now, you will be able to do something like this:
`@product.image.webp.url`

Of course, many browsers doesn't support webp yet. So don't expect to see anything in Firefox or IE.

**Comment by bitflingr** [comment]
I use dragonfly as a image resizer/optimzer proxy and noticed I am getting requests for WebP.  Ill try this out and report back if this works.  Thanks for the tip

**Comment by loureirorg** [comment]
Hi @bitflingr, I'm working in a way to serve webp automatically, when the browser has support, and without having to refactor the entire app. If you are interested, check this: https://github.com/markevans/dragonfly/issues/392

**Comment by bitflingr** [comment]
Ah, thanks. but since my app is a proxy I am honoring what ever is requested which normally comes from news feeds and such.  So i am already seeing requests for webp possibly due to someone not realizing what they are doing in pagespeed.

**Comment by bitflingr** [comment]
So i am trying to figure out how i can do the same resizing of images of jpeg/png/gif with webp.  I imagine i would have to right a processor to do all the things i currently do with imagemagick.  Otherwise maybe convert the webp to jpeg and resize it then?

**Comment by loureirorg** [comment]
@bitflingr I don't know if I understand correctly your question, but you can do something like:
```ruby
@my_record.image.convert('some imagemagick command').webp.url
```
or 
```ruby
@my_record.image.thumb('80x60').webp.url
```
or
```ruby
@my_record.image.encode(:jpg).convert('some imagemagick command').webp.url if @my_record.image.format == :webp
```

Just do a chained method calling.

**Comment by bitflingr** [comment]
cwebp seems to only output to webp.  I have built an image proxy using `Dragonfly` that can resize images on the fly.  I do not store them except for caching purposes with a short TTL.  Therefore when i get a request for a jpeg at some site, i return jpeg, same for .gif and .png.  I would like to do the same with .webp.  The only way i can see this working is if i recompile imagemagick with webp support and install it on my servers.

```bash
cd /tmp
mkdir imagemagick
cd imagemagick
sudo apt-get build-dep imagemagick
sudo apt-get install libwebp-dev devscripts
apt-get source imagemagick
cd imagemagick-*
debuild -uc -us
sudo dpkg -i ../*magick*.deb
```

I would like to avoid that only because i think it can be done in code I just do not know what my first step is.  I am reading up on making your own processors so that is where i am currently at.

**Comment by bitflingr** [comment]
So i recompiled my imagemagick to support webp via homebrew and i had to add the following to get this to work.

```ruby
        if new_image.ext == 'webp'
          content_type :'image/webp'
          new_image.data
        else
          new_image.to_response(env)
        end
```

normally `.to_response(env)` works but when it is .webp the content-type is octetstream and i end up downloading the file.  So i had to force the content_type to be 'image/webp' in order for it to work.  Just what i am running into personally.
