### ISSUE TITLE
Default url_format of "/:job/:name" is problematic.

### ISSUE THREAD

**Issue by idyll** [markevans/dragonfly#310]
The new default url_format of "/:job/:name" has been causing me all sorts of heartache and woe since upgrading to 1.0.2.

The two concerns I have are:

 1. I think the default should come with a prefix as any route with two parts is subject to being incorrectly interpreted as being a dragonfly request. When this happens you will get a JSON parse error in the middleware which instead of doing a ```'X-Cascade' => 'pass'``` fails and 404s.

 1.  When you name an app it creates an instance of the app. So even if you change the ```url_format``` in that instance, you still need to set it in the base config or dragonfly will try to consume routes it should no longer be interested in.

Since this has the potential to break apps out there if there is a change I think the best option is to instead change the rails config script to add a comment to alert a user of these two pitfalls and set a default that is not ```/:job/:name``` say ```/media/:job/:name``` for example.

I think the documentation (and maybe the read me) should get updates to remind the user of this default and that changing it on a named instance still won't solve the problem.

If this makes sense I will submit a pull request that makes these changes.

**Comment by markevans** [comment]
closing this now as it was an upgrade problem
