### ISSUE TITLE
Attachment `changed?` is not called

### ISSUE THREAD

**Issue by waiting-for-dev** [markevans/dragonfly#324]
Hi,

I'm trying to implement with Rails an observer to do something when a dragonfly attachment is changed. I have following code:

    class FileObserver < ActiveRecord::Observer
      observe :static_image
      def before_save(model)
        unless model.dragonfly_attachments.empty?
          model.dragonfly_attachments.each_pair do |accessor, attachment|
            if attachment.changed?
              Rails.logger.debug 'Hello'
            end
          end
        end
      end
    end

But, when I change the attachment, the logger code never is run. Shouldn't `attachment.changed?` return true? If I put the logger line outside the if block, this is indeed logged.

Is it a bug or `changed?` is expected to behave different that how I guess?

Thanks.

**Comment by markevans** [comment]
closing - please reopen if there is still an issue here
