### ISSUE TITLE
[bug] Dragonfly does not handle temporary files properly 

### ISSUE THREAD

**Issue by MaG21** [markevans/dragonfly#330]
There is a bug in the *TempObject* class, one can not use temporary files with dragonfly without losing the filename. This is possible because the *TempObject* class assumes Ruby's standard implementation for temporary files defines an attribute called `original_filename`. Turns out, rails it's the one that define that method.

Monkey Patch
For this monkey patch, one must set the value of the `originale_filename` attribute manually.

```ruby
class Tempfile
	def original_filename
		@original_filename
	end
	
	def original_filename=(name)
		@original_filename = name
	end
end
```
Later I'll be making a push request fixing the *TempObject* class to handle this case properly.

**Comment by markevans** [comment]
this isn't a bug - Dragonfly only uses original_filename if it exists https://github.com/markevans/dragonfly/blob/master/lib/dragonfly/temp_object.rb#L66
Depending on what you're doing, you should use `name`

**Comment by MaG21** [comment]
Hello!

I believe the issue is still there, maybe it's not a bug per se, though it is a misbehaviour :3.

In a few hours I'll edit this comment and make a more appropriated explanation of my concerns regarding `Tempfile` s.
