### ISSUE TITLE
Dynamic default image

### ISSUE THREAD

**Issue by romansklenar** [markevans/dragonfly#332]
Is there currently a way I can specify default image dynamicly based on record's attribute value?
It'd be useful a lot in cases like _"I wanna show default avatar based on user's gender"_. Example:

```ruby
class User < ActiveRecord::Base
  enum gender: [:male, :female]

  dragonfly_accessor :avatar do
    default Proc.new { "public/images/user_gender_#{gender}.png" }
  end
end
```

**Comment by markevans** [comment]
default is intended to be simple - anything more complicated should use jarinudom's method, i.e. use a helper or decorator, as this is more flexible and app-specific
