### ISSUE TITLE
0.9.15 URL stops working in 1.0 when includes encode task

### ISSUE THREAD

**Issue by semaperepelitsa** [markevans/dragonfly#341]
Encode task format has changed in 1.0 from `["e", :jpg]` to `["p", :encode, :jpg]`. The former is no longer recognized. That means, potentially all URLs can break when updating from the latest 0.9 up to 1.0. We have an option of enabling legacy marshal-encoded URLs but this breaks regardless.

Demo:

```ruby
gem 'dragonfly', '0.9.15'
require "dragonfly"

app = Dragonfly[:images]

p app.fetch("foo").encode(:jpg).to_a # [["f", "foo"], ["e", :jpg]]
p Dragonfly::Job.from_a([["f", "foo"], ["e", :jpg]], app) # ok
```

```ruby
gem 'dragonfly', '1.0.4'
require "dragonfly"

app = Dragonfly.app

app.configure do
  plugin :imagemagick
end

p app.fetch("foo").encode(:jpg).to_a # [["f", "foo"], ["p", :encode, :jpg]]
p Dragonfly::Job.from_a([["f", "foo"], ["e", :jpg]], app) # Dragonfly::Job::InvalidArray error
```

**Comment by markevans** [comment]
yes, I'm afraid I have no idea of an easy fix for this. I'm sorry if it's been a big problem with upgrading. I'll close this now as it was an upgrade problem a year ago - in the future I may incorporate better support for custom routes, so that this problem is mitigated for future upgrades
