### ISSUE TITLE
Non-thumbnailable images / corrupt images

### ISSUE THREAD

**Issue by jrz** [markevans/dragonfly#343]
Hi,

How should I handle for files which I cannot generate a preview for? And how can/should I handle images which are corrupt? (I'd like to show at least an image for a specific filetype)

**Comment by markevans** [comment]
hi - please direct questions like this to the google group, as it's not really an issue.
the analyser image.format actually analyses the the image, whereas image.ext only gives the file extension. maybe if these don't coincide it implies corrupt?
