### ISSUE TITLE
Retained image hidden field has no effect in Rails 4

### ISSUE THREAD

**Issue by bodrovis** [markevans/dragonfly#348]
Hello.
I've tried to use `<%= f.hidden_field :retained_image %>` in my app but it seems to have no effect: when I click Submit and validation fails the `file_field` value clears (however `retained_image` does have some value).

I've put `:retained_image` to the `permit` method in the controller but it didn't help.

Using Rails 4 and Ruby 2.

**Comment by luisico** [comment]
Any update on this issue? Having the same problem on rails 4.1.9, ruby 2.2.0, dragonfly 1.0.7. Thanks

**Comment by brendon** [comment]
Ok, so maybe this was just me, but are any of you using .becomes()? I was using it to standardise my url's with STI simple_form's and .becomes seems to wipe out the retained attributes.

In the end I used the `:as` and `:url` options of `simple_form_for` in order to use .becomes for the url but not for the other parts of the form.

**Comment by carpet** [comment]
@Digital-Learner Did you get to the root of this as I thought I had a similar problem, but I think it may be from a misunderstanding of how the retained_file attribute works.

From what I can see in the code you posted you are getting a value populated in the retained_image hidden field when validation fails - you just won't see a file in your Choose File input. If you attempt to submit the form after correcting your validation errors but without choosing another file from the file dialogue window you should find that the form submits and your original file is uploaded.

**Comment by antulik** [comment]
My .retained_image is nil, but model has image.

After looking a bit more 

```ruby
object.dragonfly_attachments[:image]
# => <Dragonfly Attachment uid="2015/07/09/9tqgvujl5x_1.jpg", app=:default>

object.dragonfly_attachments[:image].retained_image
# => nil

object.dragonfly_attachments[:image].retained_attrs
# => nil

object.dragonfly_attachments[:image].retained?
# => false
```

**Comment by benbws** [comment]
I was having similar issues with the `retained_<attribute_name>` just seemingly not working and coming back blank but I found that I needed to define `:retained_<attribute_name>` in the `permit()` list along with `:<attribute_name>`.

e.g. I added a simple 'image' field to my users table to allow an avatar to be uploaded (I'm using devise) so my `reistrations_controller.rb` now looks like:

```
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    dashboard_path
  end

  def sign_up_params
    params.require(:user).permit(:email, :image, :retained_image, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :image, :retained_image, :remove_image, :password, :password_confirmation, :current_password)
  end
end
```

Note the `:retained_image` (and `:remove_image` for the update method) within the `permit()` list. That's what made it work.

**Comment by gudata** [comment]
I am testing with Rails 5.0.0 and there is no retained value between the requests.

**Comment by thedarkside** [comment]
Works with Rails 5.0.1
Keep in mind that the hidden field gets only a value if it is permitted in your strong parameters!

**Comment by bodrovis** [comment]
Unfortunately this is still not working as expected - I've tested it today with Rails 5. Here is a sample app to reproduce the problem https://github.com/bodrovis/TutsPlusSource/tree/master/uploading_with_dragonfly

Steps:

1. Clone it
2. Install gems, run migrations, boot the server
3. Navigate to the main page and click Add
4. Choose some image and leave text fields empty
5. Click submit
6. You will be redirected back to the form with some errors being displayed (saying that text fields can't be empty)
7. Hidden field with retained image should have a value
8. Enter some text in the text fields and send form once again
9. You will be redirected to the main page with new album created, however, the chosen image will not be displayed

This effectively means that even though hidden field does have a value, it is not being stored anywhere afterwards.

**Comment by markevans** [comment]
it seems that retained_image is working ok, however it's not quite working properly when combined with the "copy_to" functionality.
In your code, if you uncomment line 2 in _album.html.erb https://github.com/bodrovis/TutsPlusSource/blob/master/uploading_with_dragonfly/app/views/albums/_album.html.erb#L2 it works fine. In the meantime, I'll have to think a bit about how retained_xxx should work when combined with "copy_to"

**Comment by bodrovis** [comment]
Yeah, this seems to be the cause. That's not a huge problem though.

P.S. A new article on Dragonfly is coming really soon at TutsPlus.

**Comment by markevans** [comment]
great!
