### ISSUE TITLE
Check if Dragonfly file exists before fetching it

### ISSUE THREAD

**Issue by YOUConsulting** [markevans/dragonfly#350]
I'm retrieving the Dragonfly file with `Dragonfly[:images].fetch(uid)` but if I already deleted the file I'm getting `Dragonfly::DataStorage::DataNotFound` which is logical because I'm trying to fetch a file that is deleted. 

The file is automatically deleted when send to the Backend, but if an error occurs somewhere while processing the form I return to index and the system will try to upload it again.

So I'm currently fixing it like this:

      file = Dragonfly[:images].fetch(uid) rescue ""
      Backend.add_attachment(file.name, file.data, token: @user.token) if file
      Dragonfly[:images].destroy(uid) rescue "" # Delete the file after uploading to Backend

But it would be better if I could do something like this

      file = Dragonfly[:images].fetch(uid) if Dragonfly[:images].exists?(uid)
      if file
        Backend.add_attachment(file.name, file.data, token: @user.token) 
        Dragonfly[:images].destroy(uid)
      end

**Comment by markevans** [comment]
I don't want to add this to the datastore spec, however it could be added to an individual datastore, e.g.
Dragonfly.app.datastore.exists?(uid)
Feel free to do a pull request - I'll close this for now
