### ISSUE TITLE
Articles about Dragonfly

### ISSUE THREAD

**Issue by bodrovis** [markevans/dragonfly#351]
Hello!

Recently I have written two articles for Sitepoint that cover Dragonfly:

* http://www.sitepoint.com/file-uploads-dragonfly/ - this is the main one
* http://www.sitepoint.com/asynchronous-file-uploads-rails/ - this covers many details about Async uploading, but still backed by Dragonfly

Maybe you would like to add one (or both) of these links somewhere to the docs.

Cheers!

**Comment by kubakrzempek** [comment]
The first one is really great, helps you get started with dragonfly easily.

**Comment by markevans** [comment]
sorry for the delay - thanks these are great. I've added them to a new "articles" wiki see link from README and will start adding new articles here.

**Comment by bodrovis** [comment]
Cool!
