### ISSUE TITLE
Update documentation with example for uploading multiple images

### ISSUE THREAD

**Issue by toymachiner62** [markevans/dragonfly#354]
Can the documentation on using dragonfly with rails be updated to have an example on how to upload multiple images at one time?

Here's the solution I came up with, but it took me wayy too long to figure it out and it's not as elegant as the rest of the examples i've found on using dragonfly.

http://stackoverflow.com/questions/24988265/trying-to-upload-multiple-files-document70285786863740-expected-got-action

**Comment by Vizakenjack** [comment]
Support this. What is the best way to multiple file upload? Also, I'd like to use polymorphic model.

**Comment by toymachiner62** [comment]
The link i added contains how I solved the multiple file upload problem. Not sure if there's a better way.

**Comment by uhlenbrock** [comment]
I have used the following jQuery plugin. It just hits a create controller action for each file uploaded: https://github.com/johnlanz/jquery-fileuploader

**Comment by markevans** [comment]
Unfortunately I can't add documentation for all the different use cases in the core documentation, however I've just added an "Articles" wiki page (linked to from the README) that you can add tutorials/guides to if they're good. The ideal is for someone to do a blog/tutorial and link to it :)
