### ISSUE TITLE
Proper use of dragonfly with Heroku and S3

### ISSUE THREAD

**Issue by Plaristote** [markevans/dragonfly#356]
Greetings,

I use Dragonfly in a Heroku app along with a S3 bucket. Right now, we have "high response time" errors popping in our mail accounts like crazy: obviously we did something wrong. In our current process, we always generate a thumbnail every time the Heroku server receives a request requiring it: though it's only asked once per geographical location thanks to Cloudfront, it's still way too much for us.

We'd like to know what's the correct process to implement Dragonfly-powered thumbnails along with S3 and Cloudfront.
We'd like to have a system in which thumbnails are generated on the fly, rather than after the upload, if possible, and we'd like to have them generated only once in a lifetime.

**Comment by uhlenbrock** [comment]
I know this is a bit late, @Plaristote but here is an excellent tutorial on setting up a custom origin with Cloudfront: http://www.happybearsoftware.com/use-cloudfront-and-the-rails-asset-pipeline-to-speed-up-your-app.html

**Comment by Plaristote** [comment]
It's been a while, but we've actually set the problem aside and only recently brought it up again, so you're right on time :D ! Thanks for the link, it's exactly what I was looking for !

**Comment by caifara** [comment]
We've run into some problems with cloudfront: each cloudfront edge server creates its own cache requesting it from origin. As dragonfly sometimes has a lot of work to do, this sometimes slowed down responses enormously. I just setup keycdn which uses a [POP shield](https://www.keycdn.com/blog/new-feature-origin-shield/) to overcome this problem. No results yet, but in theory this should solve our problem. Same kind of setup as mentioned above, but you need to activate the shield (on the provider) if you want to use it.

**Comment by uhlenbrock** [comment]
That is good info, @caifara, I didn't realize that there was a distinct request for each edge server. Thanks!

**Comment by MSchmidt** [comment]
@caifara Does keycdn keep the cached images forever (or at least some really long time) so I can make sure no further requests hit my origin server? My issue with CloudFlare is that they drop the cached files rather quickly if they don't get accessed frequently.

**Comment by caifara** [comment]
@MSchmidt I'm having a good experience with them (now that I've altered some of their settings), I don't think I'm hitting origin anymore

**Comment by uhlenbrock** [comment]
@MSchmidt & @caifara Be sure to set your response headers (http://markevans.github.io/dragonfly/cache/) to the desired cache duration, which KeyCDN should respect (https://www.keycdn.com/blog/expire-header-and-cache-control/).

**Comment by caifara** [comment]
@uhlenbrock @MSchmidt It does only if you get some settings correct if I remember correctly, it tends to override origins cache headers otherwise.

**Comment by MSchmidt** [comment]
@uhlenbrock @caifara if I understand it correctly it overrides the headers between CDN and client only. So clients will hit the CDN more frequently but the origin should still be left alone for the defined time.

**Comment by caifara** [comment]
@MSchmidt @uhlenbrock Just looked it up, for a pull zone to a rails backend (refinerycms), I have changed the following settings (don't know if they're all needed, do know that it took some time until it worked like we wanted).

* change the "expire" setting to 0
* enable "origin shield"
* disable "ignore cache control"
