### ISSUE TITLE
Caching problem

### ISSUE THREAD

**Issue by jakubstraka** [markevans/dragonfly#363]
Hi!

I have a problem with Caching and Symlink. I have a simple app (Rails 4.1.4, mongoid, Rack::Cache) and images are being processed everytime aftery each deploy (if they are not saved in the browser cache).

So on every image I get X-Rack-Cache: miss, store. 

I've noticed that then image is saved in current/tmp/cache (and some subfolders) and current/tmp/dragonfly is just empty.

Using Capistrano Symlink like this
```
# Dragonfly
namespace :dragonfly do
  desc "Symlink the Rack::Cache files"
  task :symlink, :roles => [:app] do
    run "mkdir -p #{shared_path}/tmp/dragonfly && ln -nfs #{shared_path}/tmp/dragonfly #{release_path}/tmp/dragonfly"
  end
end
after 'deploy:update_code', 'dragonfly:symlink'
```

Thank you in advance!
Jakub

PS. Not sure if it belongs here or to Google Groups?

**Comment by markevans** [comment]
you need to change tmp/dragonfly to tmp/cache in your capistrano task

That code would have been copied from old dragonfly docs, which had cached files saved to tmp/dragonfly, but in rails 4, switching rack_cache on puts files into tmp/cache
I removed capistrano tasks from the docs as it was too complicated to support so many different deployment strategies with so many different versions of rails/dragonfly
