### ISSUE TITLE
Replace uploaded file on S3

### ISSUE THREAD

**Issue by khoan** [markevans/dragonfly#365]
```ruby
irb> Dragonfly::VERSION # => "1.0.5"
irb > Mongoid::VERSION # => "4.0.0"
irb> bam = Bam.new(file: Pathname.new('/path/to/file.png'))
irb> bam.save
curl -I bam.file.remote_url # => HTTP/1.1 200 OK
irb> bam.file = Pathname.new('/path/to/file.png')
irb> bam.save
curl -I bam.file.remote_url # => HTTP/1.1 403 Forbidden

Dragonfly.app.configure do
  datastore :s3,
    fog_storage_options: { path_style: true },
    # ...
end

class Bam
  include Mongoid::Document
  extend Dragonfly::Model

  field :file_uid
end
```

Correct me if I'm wrong, so when I set an existing attachment with the same file name, this line
[dragonfly/model/attachment.rb#78](https://github.com/markevans/dragonfly/blob/v1.0.7/lib/dragonfly/model/attachment.rb#L78) will remove after it's uploaded. But if we remove previous file and reupload, then it's correct.

**Comment by markevans** [comment]
yes, every time you set the accessor and save

bam.file = xxxx

bam.save

it will destroy the previous one (if it existed) and re-upload.

Please use the google group for non-issue questions
