### ISSUE TITLE
Replace use of `` with a form of system that does not spawn a shell

### ISSUE THREAD

**Issue by fcheung** [markevans/dragonfly#369]
At the moment dragonfly uses backticks to execute shell commands. Would there be interest in moving to system, in particular the form of system that does not spawn a subshell ?

For example instead of

    `convert -resize 20x10 #{old_path} #{new_path}`

    system("convert", "-resize", "20x10", old_path, new_path)

The primary reason I'd like to do this is security: spawning a shell gives you way more rope to hang yourself with, whether it be not escaping things properly or vulnerabilities in the underlying shell (Hi shellshock!)

It would restrict things - you wouldn't be able to, for example, have an processor that strung together multiple shell commands.

At the very least I would like this to be an option. I'd be happy to work on this if there is interest

**Comment by bitflingr** [comment]
I for one have been noticing a problem with Zombie processes! ZOMG!  It is hard to trace down but when running ```ps aux | grep Z``` I can see defunct shell process but it then quickly removed.  I also have seen a correlation in my graphs between an increase in Zombie processes and System CPU going waaaay up.  At that point I have to restart my Ruby app to get it to recover.  I was thinking of wrapping my main dragonfly calls with ```Signal()``` but was wondering if you were heading down this direction as well.

Thanks

**Comment by bitflingr** [comment]
Ah, I see you are using open3.  So I am back to square one :)

**Comment by markevans** [comment]
yeh - it doesn't use backticks - this is just for Ruby 1.8.7, and support for 1.8.7 will be removed at some point soon anyway. It uses popen3 https://github.com/markevans/dragonfly/blob/master/lib/dragonfly/shell.rb#L46
you can't have a processor that strings together multiple shell commands, unless you explicitly say so - see http://markevans.github.io/dragonfly/processors/#implementing-the-processor "Using shell commands"
