### ISSUE TITLE
Fallback image

### ISSUE THREAD

**Issue by BrandonMathis** [markevans/dragonfly#371]
Can we add the ability to configure an application-wide fallback image when dragonfly cannot fine a file using the storred uid?

**Comment by elfassy** [comment]
for now you can set a default per attribute. It's a bit more work but allows you to set different default images

```ruby
class Photo
  dragonfly_accessor :image do
    default 'public/images/default.png'
  end
end
```

you'll need to also add to your config

```
fetch_file_whitelist [              # List of allowed file paths when using fetch_file (strings or regexps)
  /public/
]
```

**Comment by markevans** [comment]
ditto what elfassy said (actually you shouldn't need to add to the fetch_file_whitelist as the "default" helper should do this for you)
I'd rather not add an application-wide fallback image as it's quite an application-specific need, but the default helper should help to some extent
