### ISSUE TITLE
How to show full-size image instead of downloading it?

### ISSUE THREAD

**Issue by Vizakenjack** [markevans/dragonfly#372]
I have a model:

    class Image < ActiveRecord::Base
      include Rails.application.routes.url_helpers
      belongs_to :adv
    
      dragonfly_accessor :content do
        copy_to(:thumb){|a| a.thumb('145x110#') }
      end
    
      dragonfly_accessor :thumb
    end

But if I provide direct links to an image:

    link_to("image", image.content.url)

It just starts to download it. How can I make it to show in browser window?

**Comment by Vizakenjack** [comment]
Ok, I have found an issue. I'm using single model for a multiple image upload. Looks like dragonfly doesn't work well in this case.

Controller: 

    @article = Article.new(article_params)
    params[:article][:images].each do |image|
      @article.images << Attachment.create(original: image.tempfile, original_name: image.original_filename)
    end

Models:

    class Attachment < ActiveRecord::Base
      belongs_to :attachable, polymorphic: true
      dragonfly_accessor :original
    end

    class Article < ActiveRecord::Base
      has_many :images, as: :attachable, class_name: "Attachment", dependent: :destroy
    end



View:


    <%= f.file_field :images, :multiple => true %>

**Comment by bodrovis** [comment]
@Vizakenjack It can support multiple uploads with no problems. I've written a tutorial about that some time ago: http://www.sitepoint.com/asynchronous-file-uploads-rails/ Hope that helps

**Comment by markevans** [comment]
thanks @bodrovis
