### ISSUE TITLE
Remove all uploaded files

### ISSUE THREAD

**Issue by ineu** [markevans/dragonfly#376]
Sorry if the question is already answered, but I couldn't find it in docs or issues.

Sometimes in tests I need to upload real files instead of just setting `image_uid`. After tests pass I end up with garbage files, so I need to remove them. Is there better way than
```ruby
config.after :suite do
  FileUtils.rm_rf Dragonfly.app.datastore.root_path
end
```

**Comment by markevans** [comment]
yes - you can use the memory data store http://markevans.github.io/dragonfly/data-stores/#memory-data-store
in future please use the groups for this kind of question.
