### ISSUE TITLE
Content#close not being called by Rack

### ISSUE THREAD

**Issue by heymatty** [markevans/dragonfly#378]
I see that Job#close was moved to Content#close in this commit https://github.com/markevans/dragonfly/commit/56780f730f8ef3a6215c211cbb565f8a74568d55#diff-a95817a0b14973e13e55d71091dfc0da

Dragonfly::Server is returning a Job object for Rack's expected 'body' response. Job doesn't respond to #close.

Am I missing something here or is this the expected behavior?

**Comment by markevans** [comment]
no, you're not missing something. at first glance this looks like a bug!!
Thanks for pointing out. I'll try and get on the case asap (I've been away hence delayed response)
