### ISSUE TITLE
Validations break when file is missing

### ISSUE THREAD

**Issue by chrise86** [markevans/dragonfly#388]
For some reason some files that were previously uploaded by a user have disappeared (that's my own issue), but now when updating the model that owns those images (User in this case), I get a 500 error along with:

```
Dragonfly::Job::Fetch::NotFound <uid> not found
```

and an extensive error backtrace.

While I could watch and rescue from such errors, the fact that I'm getting a 500 from this doesn't seem right to me.

I guess using `if: :image_changed?` on the validations would help, but I thought I should mention this anyway.

**Comment by pnomolos** [comment]
I am also having this issue - apart from the `if: :image_changed?` suggestion, has anything bee done about this?

**Comment by markevans** [comment]
no - Dragonfly only raises an error - it's up to the surrounding application to do what it will with it - in the above case it returns 500.
the other thing to do is to manually wipe the image_uid column, otherwise it's out of sync with the fact that the images don't exist
