### ISSUE TITLE
x-amz-meta-json header: value must be us-ascii

### ISSUE THREAD

**Issue by mkhatib** [markevans/dragonfly#389]
Not sure what Dragonfly uses the x-amz-meta-json header to set in it, but I am getting an error when someone tries to upload a file that has some Arabic characters like `صورة.jpg`

    Excon::Errors::BadRequest (invalid x-amz-meta-json header: value must be us-ascii)

To reproduce have S3 setup for uploads from dragonfly and try uploading an image with Arabic characters.

Anyway to configure dragonfly to remove these characters before sending them to Amazon?

**Comment by budu** [comment]
+1 same problem with any UTF8 character

**Comment by tricknotes** [comment]
This issue will be fixed by https://github.com/markevans/dragonfly-s3_data_store/pull/18 .
