### ISSUE TITLE
validation of property format of image failed with error Command failed

### ISSUE THREAD

**Issue by ryanlion** [markevans/dragonfly#390]
hi. there guys.

 

I am using dragonfly gem to save image, after the image is uploaded, I encountered this issue.

My development machine is a MAC. I am relatively new to rails, your help will be appreciated.

 

DRAGONFLY: shell command: 'identify' '-ping' '-format' '%m %w %h' '/var/folders/0z/j3d_bsl11dz8m8zl9vpv30vr0000gn/T/RackMultipart20150228-7327-ljx0ih'
DRAGONFLY: validation of property format of image failed with error Command failed ('identify' '-ping' '-format' '%m %w %h' '/var/folders/0z/j3d_bsl11dz8m8zl9vpv30vr0000gn/T/RackMultipart20150228-7327-ljx0ih') with exit status 127 and stderr sh: identify: command not found

 

Here is the model class

 

class OrderItem < ActiveRecord::Base.extend Dragonfly::Model
    dragonfly_accessor :image
    
    validates_size_of :image, maximum: 500.kilobytes,
    message: "should be no more than 500 KB", if: :image_changed?
    
    validates_property :format, of: :image, in: [:jpeg, :jpg, :png, :bmp], case_sensitive: false,
    message: "should be either .jpeg, .jpg, .png, .bmp", if: :image_changed?
end

 

and here is the migration file for the model class

 

class CreateOrderItems < ActiveRecord::Migration
  def change
    create_table :order_items do |t|
      t.string :itemUUID
      t.string :order_id
      t.string :product_name
      t.string :packing
      t.string :image_uid
      t.string :title

      t.timestamps
    end
  end
end

**Comment by markevans** [comment]
Hi - it can't find imagemagick. You need to install it or if it's installed
and still can't find it, see
http://markevans.github.io/dragonfly/imagemagick/#configuration

**Comment by ruimigueltrigo** [comment]
@markevans , the link is now [http://markevans.github.io/dragonfly/imagemagick](url)

and add the missing comma on the second line on the wiki, please.
```
Dragonfly.app.configure do
  plugin :imagemagick,
    convert_command: "/opt/local/bin/convert"**(COMMA HERE)**    # defaults to "convert" 
    identify_command: "/opt/local/bin/identify"  # defaults to "identify"
end
```

**Comment by markevans** [comment]
done 👍
