### ISSUE TITLE
Automatically serves WebP when browser has support

### ISSUE THREAD

**Issue by loureirorg** [markevans/dragonfly#392]
How do I force DragonFly convert to and serve WebP when the browser has support? WebP images are about 25% lower than jpg, so its a quite appealing idea ;) And I want to do this on-the-fly, not when saving the image.

My problem its not to discover whenever a browser has support or not, but create a callback that generates a new version and serve it.

I'm trying to use `before_serve` (http://markevans.github.io/dragonfly/configuration/) to do the job. 

```ruby
# config/initilizers/dragonfly.rb
Dragonfly.app.configure do
...
  before_serve do |job, env|
    if job.content.mime_type != "image/webp"
      job.content.shell_update do |old_path, new_path|
        "/usr/bin/cwebp #{old_path} -o -"
      end
    end
  end
end
```

The problem is: job.content is always empty. My guess is because its called before the steps be processed. So, how do I get the file name of the served file right before it be served?

**Comment by loureirorg** [comment]
I got it! At least I guess (I need to check if I'm really getting webp for Chrome and jpg for Firefox).

```ruby
# config/initilizers/dragonfly.rb
Dragonfly.app.configure do
...
  processor :webp do |content, *args|
    content.shell_update do |old_path, new_path|
      "/usr/bin/cwebp #{old_path} -o #{new_path}"
    end
  end

  before_serve do |job, env|
    if env['HTTP_USER_AGENT'] =~ /[^\(]*[^\)]Chrome\//
      job.steps << Dragonfly::Job::Process.new(job, "webp")
    end
  end  
end
```

**Comment by benpickles** [comment]
You should probably use content negotiation rather than whitelisting specific browsers. This might just do it:

```ruby
env['HTTP_ACCEPT'] =~ /image\/webp/
```

**Comment by loureirorg** [comment]
thanks @benpickles. I was thinking in use the [browser gem](https://github.com/fnando/browser), but this is too way better ;)

**Comment by loureirorg** [comment]
Ok, I discover that unfortunately my solution only works when *not* using a cache (like Varnish or Rack-Cache). 

The problem: open an image in Chrome, Rails will call DragonFly (and trigger the custom code) which will generate a webp version and save this version on the server as a cache. After, open the same image link in Firefox - Rails will get the cached file (a webp file), without trigger the custom code and serve this webp file instead of the original.

I'm thinking to override `url`, or create an alternative version called `webp_url`. This method will check if the browser have webp support and provides a converted image if have support, or bypass to the `url` if not.

Example:
```ruby
@product.image.thumb('80x60').webp_url
```

The implementation will be something like that:
```ruby
class Dragonfly
  def webp_url
    env['HTTP_ACCEPT'] =~ /image\/webp/ ? self.webp.url : self.url
  end
end
```

Is there a better solution to (without change my entire app code) send a webp version when the browser have support?

**Comment by loureirorg** [comment]
now I'm stucked and can't go any further :( 

This is my code:

```ruby
Dragonfly.app.configure do
  ...
  # create a "webp" method: @product.image.thumb('80x60').webp.url
  processor :webp do |content, *args|
    content.shell_update do |old_path, new_path|
      "/usr/bin/cwebp #{old_path} -o #{new_path}"
    end
  end
end

module Dragonfly
  class Job
    def url
      if env.nil?
        # we are in a console, not in a browser
        super
      else
        # check webp support and if attachment its an image (we won't convert a non-image file)
        if env['HTTP_ACCEPT'] =~ /image\/webp/ && content.mime_type ~= /image/
          self.steps << Dragonfly::Job::Process.new(self, "webp")
        else
          super
        end
      end
    end
  end
end
```

There's many problems with my solution:
1) `env`doesn't exists and I don't know how to obtain the request environment here
2) `content`is blank so `content.mime_type` always returns 'application/octet'. I believe that is because `self.steps` aren't processed yet (maybe its necessary to do something like `while steps.shift.apply do end`)
3) `super` doesn't work here and I don't understand why (`NoMethodError: super: no superclass method `url'`)

I will close this topic, but if anyone can help me, I will appreciate.

**Comment by benpickles** [comment]
I think using the `Vary` response header would fix your HTTP cache issue and prevent you having to monkeypatch Dragonfly.

**Comment by loureirorg** [comment]
You are a genius @benpickles! I will try that, although I don't know very well this header.

**Comment by benpickles** [comment]
Let me know how it goes, it looks to me like this functionality could be useful and appropriate to have either in a plugin or Dragonfly itself.
