### ISSUE TITLE
Format validator fails even though format is correct

### ISSUE THREAD

**Issue by asgerb** [markevans/dragonfly#393]
The format validator returns an error even though the format is correct.

The following validation setup

``` Ruby
validates_property :format, of: :file, in: ['jpeg', 'gif']
```

returns an error hash when uploading for instance a `.gif`:

``` Ruby
{:file=>["format is incorrect. It needs to be one of 'jpeg', 'gif', but was 'gif'"]}
```

Using  `dragonfly (1.0.7)` and `rails (4.2.0)`.

**Comment by pjmorse** [comment]
I'm also seeing this in dragonfly 1.0.7 and rails 3.2.22.

**Comment by patizivs** [comment]
It is an old thread, but anyways. Format validation works only for images, for other types, like word or excel files, format validation is delegated to soffice, so if it is not present, then validation fails with format is incorrect message.  I think this is not an issue, just documentation needs more detailed information, how validation works.

**Comment by markevans** [comment]
that's right - `validates_property :format` simply calls `.format` on the `file` attachment, which in turn is a registered analyser from the imagemagick plugin http://markevans.github.io/dragonfly/imagemagick#analysers
which uses imagemagick to analyse the content and get the "format".

You can use 'ext' as per http://markevans.github.io/dragonfly/models#validations for non-images, though this is just the file extension, not the actual content.

If you really want to actually analyse the content you'd need something custom (like a custom analyser using the `file --mime` command).

Or to only analyse images you can use `if: ->(model){ model.file.image? }` or something in the validation

**Comment by markevans** [comment]
@asgerb I realise this is very late but did you ever find out why 'gif' wasn't being matched with 'gif'?
If still a problem I'd need some more info to reproduce (e.g. the sample gif file that didn't work)

**Comment by asgerb** [comment]
Hey @markevans, honestly I'm not sure what the circumstances were, but it seems I went for the following solution:
```
validates_property :ext, of: :file, in: %w(tiff TIFF tif TIF jpg JPG jpeg JPEG png PNG gif GIF)
```
So maybe `format` was not working for me for some reason, but unfortunately I can't tell you much more, as I don't remember 😉

**Comment by markevans** [comment]
👍 ok thanks for the reply - I'll close for now but feel free to reopen if there's an obvious bug

**Comment by asgerb** [comment]
I've just tried to change the validation to `:format` and indeed it fails:
```
File format is incorrect. It needs to be one of 'tiff', 'TIFF', 'tif', 'TIF', 'jpg', 'JPG', 'jpeg', 'JPEG', 'png', 'PNG', 'gif', 'GIF', but was 'JPG'
```
I'll try to dig a bit deeper!

**Comment by asgerb** [comment]
Sorry, in the mean time I've gone over to using `dragonfly_libvips`, so I'll start my digging there 😉
Thanks for your time!

**Comment by markevans** [comment]
ok - I can't reproduce the problem myself, but if it helps the code to match is here: https://github.com/markevans/dragonfly/blob/master/lib/dragonfly/model/validations.rb#L21
A quick check is to open up rails console and do
`my_model.file.format` to see exactly what's returned (and why it's not matching one of the given ones)

**Comment by asgerb** [comment]
Thanks a lot, I'll let you know if I discover something!

**Comment by asgerb** [comment]
And I did, and it was of course my own fault 😄
I've got the `:file_format` field set as a `Symbol`, which means it returns a symbol for both `file_format` and `file.format`. Sorry for wasting your time!

**Comment by markevans** [comment]
ah cool glad we got to the bottom of it. No worries - thanks for finding it!
