### ISSUE TITLE
rails-4.2.2 dragonfly nginx/passenger: how to see the image ?

### ISSUE THREAD

**Issue by jerome2** [markevans/dragonfly#402]
image is now wel downloaded and stored.
in the view, i think i have to put: "= @work.image
the view of this render:
"#<#<Class:0x007fe2f1e26db0>:0x007fe2dfc7bb30> "
no image view.
lake of information for resolve it.
is it normal and where i can find how to show the image stored ?
thank you.

**Comment by benpickles** [comment]
Try:

```ruby
<%= image_tag @photo.image.thumb('400x200#').url if @photo.image_stored? %>
```

http://markevans.github.io/dragonfly/rails/

**Comment by jerome2** [comment]
works fine, thanks for quick answer. I see it in the doc now, i tink i was loose because of search in the doc what is on the readme.md... very nice gem, i'm happy with it.
have a good day (i don'y know how to close the issue post)
