### ISSUE TITLE
I don't understand the documentation around verify_urls

### ISSUE THREAD

**Issue by jaredbeck** [markevans/dragonfly#403]
I'm looking at the "Configuration" page of the documentation, and I don't understand what `verify_urls` does.

```
  verify_urls true # enabled by default, use false to disable it - adds a SHA parameter on the end of urls
```

Looking through the commit history, I'm guessing it has something to do with preventing DoS attacks?

Is there some way we can improve the documentation around this feature?

CC: @sbleon

**Comment by jaredbeck** [comment]
Closing after ~ 1 year due to inactivity.

**Comment by mtsmfm** [comment]
@jaredbeck
I also wonder what `verify_urls` is  and I've found detailed documentation for `protect_from_dos_attacks`, previous option name for `verify_urls`.

https://markevans.github.io/dragonfly/v0.9.15/file.URLs.html#Denial-of-service_attacks
https://github.com/markevans/dragonfly/blob/0d799e19e1a9ae2c4ade0315eee430a02325ce35/extra_docs/URLs.md#denial-of-service-attacks

It must be used with `secret` option to add sha parameter which only can be generated by who knows secret string.

@markevans Just FYI, you had moved the docs to somewhere but I can't find it on current doc http://markevans.github.io/dragonfly/

https://github.com/markevans/dragonfly/commit/3ed8da06736d388852ca3699ec028dbfe987d55d
