### ISSUE TITLE
mime_type is not stored

### ISSUE THREAD

**Issue by chrise86** [markevans/dragonfly#407]
According to the docs, any of the registered analysis methods can and will be stored as magic attributes. However, when storing a file `image` the attribute `image_mime_type` is not set.

**Comment by markevans** [comment]
that's because it's not an analyser method (imagemagick provides these: http://markevans.github.io/dragonfly/imagemagick/#analysers).

The other ones it sets are "name" and "size" (http://markevans.github.io/dragonfly/models/#magic-attributes)

Do you need it to be set for your use case?

**Comment by chrise86** [comment]
Ah ok. It's not essential, no. Thanks :)
