### ISSUE TITLE
Getting different ETag using custom processor

### ISSUE THREAD

**Issue by bitflingr** [markevans/dragonfly#410]
Hi,

I have a case where I pad an image requested with a blurred background of the same image.  I do this by assigning a copy of the image to a different variable and create a new processor that uses the '-composite'

```ruby
          processor :layer_thumb do |content, *args|
            args    = args.first || {}
            bg_layer = args[:bg_path] || 'red'
            content.process! :convert, "-gravity north #{bg_layer} -composite"
          end
```

When I do this i get a different `ETag:` in the response causing all requests to 200 instead of 304 for the same image.  Am I doing something wrong?  I noticed the `ETag:` header uses the signature method in `Dragonfly::Job` class, which is based on the job steps.  Is there maybe a way to override this in these cases?

Thanks

**Comment by markevans** [comment]
hi - like you say, if an arg changes at all the ETag changes. you can override response headers using the response_header configuration option (see http://markevans.github.io/dragonfly/configuration/), which you could override for a specific job, e.g.

    response_header 'ETag' do |job, request, headers|
      if job.process_steps.first.try(:name) == :layer_thumb
        # something
      else
        %("#{job.signature}") # the usual etag
      end
    end

**Comment by bitflingr** [comment]
Okay, I actually just tried that before seeing your response.  Good to know I am on the right track.  This is why I am ending up doing.
```ruby
          response_header 'ETag' do |job,request,headers|
            if job.process_steps[-2].try(:name) == :layer_thumb
              Digest::SHA1.file(job.file.path).hexdigest
            else
              job.signature
            end
          end
```

Which gets me a unique Etag for every param and source image I am using.

Thanks!
