### ISSUE TITLE
Meta files redundancy

### ISSUE THREAD

**Issue by ahmgeek** [markevans/dragonfly#412]
I am using dragon fly to upload videos/audios sometime merged video and audio - depending on browsers blobs - so if my browser is chrome, I merge both of them in a server worker. then I delete the audio and previous video file.
but the meta files stay at the directory, is there away to not produce a meta <code>file.yml</code>.

![screenshot from 2015-09-13 15 23 33](https://cloud.githubusercontent.com/assets/4132009/9836893/6c703bc6-5a2b-11e5-9975-a022b462bcf8.png)

**Comment by markevans** [comment]
you can pass a `store_meta: false` option to the file datastore
