### ISSUE TITLE
suppressing image magick shell command output

### ISSUE THREAD

**Issue by jogaco** [markevans/dragonfly#413]
Is there any way to suppress this output?
```
DRAGONFLY: shell command: 'convert' '/tmp/dragonfly20150914-11481-149wntg.JPG' '-resize' '500x500>' '/tmp/dragonfly20150914-11481-1m3vonu.jpg'
```

**Comment by kyanny** [comment]
`Dragonfly.logger = Logger.new('/dev/null')` ?
https://gist.github.com/kyanny/4757dc5d15445f9d51e3

**Comment by markevans** [comment]
yup, or change the logger level (those outputs use logger.debug)

**Comment by jogaco** [comment]
Thanks
