### ISSUE TITLE
Data-store per model

### ISSUE THREAD

**Issue by ahmgeek** [markevans/dragonfly#415]
Can I define a datastore per model ?
I've already connect dragonfly with s3
``` 
 if Rails.env.development? || Rails.env.test?
    datastore :file,
      root_path: Rails.root.join('public/system/dragonfly', Rails.env),
      server_root: Rails.root.join('public')
  else
    datastore :s3,
      bucket_name: ENV['S3_BUCKET_NAME'],
      access_key_id: ENV['AWS_ACCESS_KEY_ID'],
      secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
      ##url_scheme: 'https'
  end
end
```
that works amazing with every attachment - images, videos etc..- 
I want to point the video model to upload to my local storage first. do some process then move it to s3, without breaking the default behavior of the uploading; to s3.

is it possible to have this feature ?

**Comment by uhlenbrock** [comment]
I think you could accomplish this by creating a separate Dragonfly app for each datastore scheme you wish to employ. Here is some more detail on configuring an app: 

- Invoke a new app with `Dragonfly.app(:app_name).configure do...`
- Invoke the accessor in the model via `dragonfly_accessor :app_name => :images`

**Comment by ahmgeek** [comment]
thanks @uhlenbrock but when I did this, I faced an end-of-input error.
```
belongs_to :contribution
  dragonfly_accessor :app_name => :videod, :video do
    storage_options do |video|
      { path: "#{Video.gen_uuid}-#{video.name}" }
    end
  end
```
expecting end-of-input

**Comment by uhlenbrock** [comment]
Reverse the order of the arguments (`:video, dragonfly_accessor :app_name => :videos`) or group the arguments (`dragonfly_accessor { :app_name => :videos }, :video`)

**Comment by ahmgeek** [comment]
*MAD HUGS* i LOVE YOU @uhlenbrock

**Comment by ahmgeek** [comment]
@uhlenbrock it throw errors about 
Rails.application.middleware.use Dragonfly::Middleware
any ideas  ?

**Comment by markevans** [comment]
have you configured the videos app to use the local data store? You don't need to mount the videos app if you're only using it to store videos before moving to S3 (is that another dragonfly accessor?)

**Comment by ahmgeek** [comment]
yeah, here's how I do it.
```
# Configure
Dragonfly.app.configure do
  plugin :imagemagick

  secret "258b69e4f66b243eecbe12c79712f8ef313ea1aef959a8d2125b6cf2e0841869"

  url_format "/media/:job/:name"

  # Keep the images cached for 60 days.
  response_header "Cache-Control", "public, max-age=5184000"


  if Rails.env.development? || Rails.env.test? || Rails.env.production?
    datastore :file,
      root_path: Rails.root.join('public/system/dragonfly', Rails.env),
      server_root: Rails.root.join('public')
  # else
  #   datastore :s3,
  #     bucket_name: ENV['S3_BUCKET_NAME'],
  #     access_key_id: ENV['AWS_ACCESS_KEY_ID'],
  #     secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
  #     ##url_scheme: 'https'
  end
end

Dragonfly.app(:videos).configure do

  secret "258b69e4f66b243eecbe12c79712f8ef313ea1aef959a8d2125b6cf2e0841869"

  url_format "/media/:job/:name"

  # Keep the images cached for 60 days.
  response_header "Cache-Control", "public, max-age=5184000"

  if Rails.env.development? || Rails.env.test? || Rails.env.production?
    datastore :file,
      root_path: Rails.root.join('public/system/dragonfly/media', Rails.env),
      server_root: Rails.root.join('public')
  end
end


# Logger
Dragonfly.logger = Rails.logger

# Mount as middleware
Rails.application.middleware.use Dragonfly::Middleware

```
and in the models, for the image model:
```
class Photo < ActiveRecord::Base
  belongs_to :contribution

  dragonfly_accessor  :image

end
```

and for the videos:
```
class Video < ActiveRecord::Base

  belongs_to :contribution
  
  dragonfly_accessor :video, :app_name => :videos do
    storage_options do |video|
      { path: "videos/#{Video.gen_uuid}-#{video.name}.webm" }
    end
  end

 dragonfly_accessor :audio, :app_name => :videos do
    storage_options do |audio|
      { path: "videos/#{Video.gen_uuid}-#{audio.name}.wav" }
    end
  end

end
it's correct, right ?

if I made the default images App store it into s3, it's throw an error.

**Comment by luizrogeriocn** [comment]
I know this is an old and closed issue. But as this helped me finding how to define custom data-stores, I guess sharing what I found might help others as well.

As pointed, you are able to define a new Dragonfly app instance called `videos` with:
 
`Dragonfly.app(:videos).configure do ... end`

The way you would want to point to this instance in your model is using an `app` option instead of `app_name` ([see here](https://github.com/markevans/dragonfly/blob/7ed572b8c1e4fd0daedd7c970a080e35c468a838/lib/dragonfly/model/class_methods.rb#L26)), like this:

```
class Video < ActiveRecord::Base
  ...
  dragonfly_accessor :video, app: :videos do
    ...
  end

 dragonfly_accessor :audio, app: :videos do
   ... 
  end
end
```

Using this approach you can define different Dragonfly apps under the same Rails application and even on engines inside that application with their own Dragonfly initializers.

Thank you, guys, for the discussion here lead me to the solution I needed. :smile:
