### ISSUE TITLE
Static versions

### ISSUE THREAD

**Issue by lnikell** [markevans/dragonfly#423]
Hello! Is any options to save all dragonfly processed images to the storage(like carrierwave)?
For example we like to use dragonfly on our project but sometimes we need to save all images to storage to create offline version of application, which will contain all necessary images.
For this case we often use carrierwawe but maybe we could use dragonfly instead.

**Comment by dlibanori** [comment]
There are several ways to do this. Checkout dragonfly [documentation](http://markevans.github.io/dragonfly).

**Comment by lnikell** [comment]
Thank you @dlibanori , but I have already read documentation, and did not find good way to do it.
I know that I could use to_file method to generate ouput file, but to make it clear I need to write special rake task which will map all object with images and generate files with all versions or I will need make it on after_save in each model with images. Both options is not good. 
Maybe you could recommend me something?

**Comment by markevans** [comment]
@lnikell did you see this bit? http://markevans.github.io/dragonfly/models/#up-front

**Comment by dlibanori** [comment]
@lnikell also [here](http://markevans.github.io/dragonfly/configuration/)

**Comment by lnikell** [comment]
@markevans  @dlibanori  Thank you for response. I think copy_to could be useful for me.
