### ISSUE TITLE
Just FYI re dragonfly-rails gem

### ISSUE THREAD

**Issue by dougharman** [markevans/dragonfly#424]
The dragonfly-rails gem listed as a Misc add-on is not searchable in Rubygems.org and the last commit in ritxi's repository (where the link points) is 4 years ago

**Comment by markevans** [comment]
thanks - yeh that's not used any more - I'm not sure what link you meant but it's not available on rubygems https://rubygems.org/gems/dragonfly-rails
Just "dragonfly" is used now
