### ISSUE TITLE
Some Dragonfly plugins to be added to the list of addons

### ISSUE THREAD

**Issue by tomasc** [markevans/dragonfly#429]
Thanks for the excellent gem.

We've made a range of dragonfly plugins -- perhaps worth adding them to the list of addons as someone might find them useful as well:

Datastores
https://github.com/tomasc/dragonfly-moped_data_store
https://github.com/tomasc/dragonfly-mongoid_data_store

Analysers & Processors
https://github.com/tomasc/dragonfly_audio
https://github.com/tomasc/dragonfly_harfbuzz
https://github.com/tomasc/dragonfly_pdf
https://github.com/tomasc/dragonfly_phantomjs
https://github.com/tomasc/dragonfly_svg

**Comment by markevans** [comment]
That's fantastic! they look really useful.

actually please feel free to add them yourself here - you can add a short summary to each if needed: https://github.com/markevans/dragonfly/wiki/Dragonfly-add-ons

It should be editable - let me know if not.

**Comment by tomasc** [comment]
@markevans added them to the list
