### ISSUE TITLE
Dragonfly not saving images

### ISSUE THREAD

**Issue by samvandamme** [markevans/dragonfly#448]
I'm having an issue getting Dragonfly to run properly while following[ this tutorial](https://www.sitepoint.com/asynchronous-file-uploads-rails/). My model has been adjusted

```
dragonfly_accessor :avatar
validates_property :format, of: :avatar, in: [:jpeg, :jpg, :png], case_sensitive: false,
                   message: "should be either .jpeg, .jpg, .png", if: :avatar_changed?
```
dragonfly.rb has the imagemagick plugin

```
Dragonfly.app.configure do
  plugin :imagemagick
  ...
```
The schema for companies has the `avatar_uid` string.
The new/edit view has an `<%= f.file_field :avatar %>`

I'm able to pick an image from my disk (a normal .jpg image file) but every time I try to save it I'm getting the following error:

```
DRAGONFLY: shell command: 'identify' '-ping' '-format' '%m %w %h' '/var/folders/vp/k1zt15v54hg2945r9xpw0x980000gn/T/dragonfly20160706-75620-wb2b34'
DRAGONFLY: validation of property format of avatar failed with error Command failed ('identify' '-ping' '-format' '%m %w %h' '/var/folders/vp/k1zt15v54hg2945r9xpw0x980000gn/T/dragonfly20160706-75620-wb2b34') with exit status 1 and stderr identify: no decode delegate for this image format `' @ error/constitute.c/ReadImage/504.
```
As the error states `no decode delegate` for this image format I print my list of supported images with the console command identify -list format

```
...
JPE* JPEG      rw-   Joint Photographic Experts Group JFIF format (80)
JPEG* JPEG     rw-   Joint Photographic Experts Group JFIF format (80)
JPG* JPEG      rw-   Joint Photographic Experts Group JFIF format (80)
JPS* JPEG      rw-   Joint Photographic Experts Group JFIF format (80)
...
```
<b>Update 07/07</b>

I figured out that ImageMagick runs good as the commands work when entered directly in the console. Further investigation led me to Dragonfly not saving my pictures. The picture can be perfectly selected on the view, but when tapping save, something goes wrong. My file names are something like `8ffx1d9pp6_file`, notice: no extension... Therefore ImageMagick doesn't recognise the type. The weird thing is that these files just open with TextEdit, the content is `IMG_7882.JPG`, the file name that was supposed to be uploaded.

**Comment by markevans** [comment]
Are you using an older version of Rails? It could be that you need to add `:html => {:multipart => true}` to the form (as it looks like it's just sending through the filename, not the contents of the file)

**Comment by samvandamme** [comment]
@markevans Thank you for your answer, I've been at this for over 2 days now and I'm going insane!
My current version of Rails is 4.2.1, and adding the multipart doesn't solve it.

**Comment by markevans** [comment]
afraid I can't help much more as I'm not familiar with the async libraries in that tutorial.
If I were you I'd use the "pry" gem and stick a `binding.pry` line at the top of the controller action that saves the image.
Then have a look at `params['your_model_name']['avatar']` and make sure it's a tempfile-like object with the correct data. If not the problem's on the front end I think (i.e. not passing the file to the back end properly)
