### ISSUE TITLE
Use ImageMagick montage?

### ISSUE THREAD

**Issue by creativetags** [markevans/dragonfly#460]
Is it possible to use the montage command from ImageMagick to tile images with Dragonfly?

**Comment by markevans** [comment]
it's not implemented in core but there's no reason why not with a custom processor http://markevans.github.io/dragonfly/processors#implementing-the-processor (see "using shell commands")

**Comment by creativetags** [comment]
Thanks, I decided not to do it in the end as it seems too complicated to get multiple images into the montage command with custom processors. I feel it's something that is beyond the scope of what you're doing with dragonfly. Thanks for your awesome work on it.
