### ISSUE TITLE
Dragonfly dirty reads...

### ISSUE THREAD

**Issue by aphillipo** [markevans/dragonfly#465]
Hello,

I have a very very low trafficked site that maybe gets a few hits per day and sometimes none.  This means that the dragonfly cache times out and causes all of the images to need to be recreated at once.

I don't mind the images being stale for the first load and recreated in the background ready for the next person; any way to configure this?

Thanks!

**Comment by markevans** [comment]
hi - what do you mean the dragonfly cache times out? If you have a caching proxy in front of it (see http://markevans.github.io/dragonfly/cache) then the cache should last as long as the "Cache-Control" header sets it to, which by default is a year

**Comment by aphillipo** [comment]
Okay this is probably my fault I'll have another look 👀
