### ISSUE TITLE
Log too noisy with Ruby 2.4.1

### ISSUE THREAD

**Issue by jogaco** [markevans/dragonfly#471]
I recently upgraded to Ruby 2.4.1 and now my log is plagued with messages of the kind:

/home/myuser/.rvm/gems/ruby-2.4.1@mygemset/gems/dragonfly-1.1.1/lib/dragonfly/temp_object.rb:55:in `initialize': Dragonfly::Content#tempfile at /home/myuser/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method Dragonfly::TempObject#tempfile

**Comment by jogaco** [comment]
Seems to be similar to this: https://github.com/thoughtbot/shoulda-matchers/issues/1006

**Comment by jogaco** [comment]
Looks like delegation to private methods is the culprit, and might even be deprecated: https://bugs.ruby-lang.org/issues/12782

**Comment by jogaco** [comment]
This is fixed by #468

**Comment by markevans** [comment]
#468 merged in now
