### ISSUE TITLE
Data URI doesn't work with file greater them few bytes

### ISSUE THREAD

**Issue by dlibanori** [markevans/dragonfly#478]
Data URI doesn't work if you get a file that its encoded version is greater them 60 bytes. I suppose it is about de subtle difference between [encode64](http://ruby-doc.org/stdlib-2.4.1/libdoc/base64/rdoc/Base64.html#method-i-encode64) and [strict_encode64](http://ruby-doc.org/stdlib-2.4.1/libdoc/base64/rdoc/Base64.html#method-i-encode64).

**Comment by markevans** [comment]
see https://github.com/markevans/dragonfly/pull/479
