### ISSUE TITLE
Adding the ability to specify headers for a URL based attachment

### ISSUE THREAD

**Issue by brendon** [markevans/dragonfly#498]
Hi @markevans, I hope all is going well in the leadup to Christmas :)

I'm looking to download files from Google Drive via dragonfly. They'll be specified by the user using the Google Drive file picker tool that returns a `file_id` and `oauth_token`. I can send these back to the server and have Dragonfly download the file from there. The trouble is that to download the file, the oauth token needs to be specified in a header:

```
GET https://www.googleapis.com/drive/v3/files/0B9jNhSvVjoIVM3dKcGRKRmVIOVU?alt=media
Authorization: Bearer <ACCESS_TOKEN>
```

See: https://developers.google.com/drive/api/v3/manage-downloads

I've had a look at the code and it appears specifying extra headers isn't currently supported. Would you be interested in having this as a feature? or do you think there's another way to do this?

I guess the biggest challenge would be working out a tidy way to pass in the extra headers. Perhaps passing a hash to the assignment method that contains say:

```
@photo.image_url = {
  url: 'https://www.googleapis.com/drive/v3/files/0B9jNhSvVjoIVM3dKcGRKRmVIOVU?alt=media',
  headers: { 'Authorization': 'Bearer <ACCESS_TOKEN>' }
}
```
would work? I'd be keen to get onto this asap, so if you had any ideas or pointers before I begin that would be really helpful :)

**Comment by markevans** [comment]
hi - I'd be reluctant to change anything with the `model.image_url=` method as this is just a convenience method that will get complicated if adding extra stuff. The place to do it would be in `fetch_url`. You could do
```ruby
photo.image = Dragonfly.app.fetch_url("https://www.goo...", headers: {"Authorization"=> "Bearer <TOKEN>"})
```
The only thing missing that isn't currently implemented is the second arg with `headers: {...` in `FetchUrl`, but it would be fairly easy to add.

**Comment by brendon** [comment]
Thanks @markevans, that makes a lot of sense. I've created a PR for this. Fairly simple. Let me know if there's anything to fix :)

**Comment by brendon** [comment]
I've tested this approach in my app now and it works well.
