### ISSUE TITLE
Quality loss on thumbnails

### ISSUE THREAD

**Issue by ghost** [markevans/dragonfly#55]
Hello there,

I really like Dragonfly alot. The only downside at the moment is the loss of quality on generated thumbnails. Is there a way to specify -quality in an options hash or alike?

Kind regards,
Marian

**Comment by acrolink** [comment]
I have a question about the .convert method i.e.

my_image.convert('-resize 320x200 -quality 95')`
`
Is the resulted images cached or is it re-generated each time the page is viewed? Thanks.
